In [ ]:
pip install openpyxl pandas numpy matplotlib

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import os
from google.colab import drive

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Aminu_Assignment/AminuInputFile.xlsx",sheet_name="Sheet1")
df.head()

,Order ID,Date,Account,Aminu SKU,Qty,Appoint. Date,Category,Unit Price,Treat Disc,Retail Disc,Base Price,GST,Final Price,Check (R/T),Unnamed: 14,Unnamed: 15,Unnamed: 16
0,2500.0,2025-11-01,A,FG - AHA Face Wash - 100ml,1.0,2025-11-12,Cleanser,1228.81,NaN,0.36,786.44,141.56,928.0,0.0,NaN,NaN,NaN
1,2500.0,2025-11-01,A,FG - Sea Salt Body Scrub - 200ml,1.0,2025-11-12,Body,2245.76,NaN,0.36,1437.29,258.71,1696.0,0.0,NaN,NaN,NaN
2,2500.0,2025-11-01,A,FG - Radiance Face Oil - 30ml,1.0,2025-11-12,Oil,3008.47,NaN,0.36,1925.42,346.58,2272.0,0.0,NaN,NaN,NaN
3,2500.0,2025-11-01,A,FG - Melting Balm Cleanser - 50ml,1.0,2025-11-12,Cleanser,1016.95,NaN,0.36,650.85,117.15,768.0,0.0,NaN,NaN,NaN
4,2500.0,2025-11-01,A,FG - Copper Peptide Serum - 30ml,3.0,2025-11-12,Serum,3898.31,NaN,0.36,7484.75,1347.25,8832.0,0.0,NaN,NaN,NaN

In [ ]:
#Task 1

In [ ]:
df=df.iloc[:, :14]
df.columns=['order_id', 'date', 'account_code', 'product_name', 'quantity','appointment_date', 'category', 'unit_price', 'treat_disc', 'retail_disc', 'base_price', 'gst', 'final_price', 'check_rt']
df.head() #removing extra columns and rename them for better data handling

,order_id,date,account_code,product_name,quantity,appointment_date,category,unit_price,treat_disc,retail_disc,base_price,gst,final_price,check_rt
0,2500.0,2025-11-01,A,FG - AHA Face Wash - 100ml,1.0,2025-11-12,Cleanser,1228.81,NaN,0.36,786.44,141.56,928.0,0.0
1,2500.0,2025-11-01,A,FG - Sea Salt Body Scrub - 200ml,1.0,2025-11-12,Body,2245.76,NaN,0.36,1437.29,258.71,1696.0,0.0
2,2500.0,2025-11-01,A,FG - Radiance Face Oil - 30ml,1.0,2025-11-12,Oil,3008.47,NaN,0.36,1925.42,346.58,2272.0,0.0
3,2500.0,2025-11-01,A,FG - Melting Balm Cleanser - 50ml,1.0,2025-11-12,Cleanser,1016.95,NaN,0.36,650.85,117.15,768.0,0.0
4,2500.0,2025-11-01,A,FG - Copper Peptide Serum - 30ml,3.0,2025-11-12,Serum,3898.31,NaN,0.36,7484.75,1347.25,8832.0,0.0

In [ ]:
df.dtypes

order_id                   float64
date                datetime64[ns]
account_code                object
product_name                object
quantity                   float64
appointment_date    datetime64[ns]
category                    object
unit_price                 float64
treat_disc                 float64
retail_disc                 object
base_price                 float64
gst                        float64
final_price                float64
check_rt                   float64
dtype: object

In [ ]:
df=df[df['order_id'].notna()] #removing all rows with missing order_id as order_id is primary key
df.head(-6)

,order_id,date,account_code,product_name,quantity,appointment_date,category,unit_price,treat_disc,retail_disc,base_price,gst,final_price,check_rt
0,2500.0,2025-11-01,A,FG - AHA Face Wash - 100ml,1.0,2025-11-12,Cleanser,1228.81,NaN,0.36,786.44,141.56,928.0,0.0
1,2500.0,2025-11-01,A,FG - Sea Salt Body Scrub - 200ml,1.0,2025-11-12,Body,2245.76,NaN,0.36,1437.29,258.71,1696.0,0.0
2,2500.0,2025-11-01,A,FG - Radiance Face Oil - 30ml,1.0,2025-11-12,Oil,3008.47,NaN,0.36,1925.42,346.58,2272.0,0.0
3,2500.0,2025-11-01,A,FG - Melting Balm Cleanser - 50ml,1.0,2025-11-12,Cleanser,1016.95,NaN,0.36,650.85,117.15,768.0,0.0
4,2500.0,2025-11-01,A,FG - Copper Peptide Serum - 30ml,3.0,2025-11-12,Serum,3898.31,NaN,0.36,7484.75,1347.25,8832.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1242,2723.0,2025-11-29,Y,FG - Skin Perfecting Serum - 10ml,3.0,NaT,Serum,830.51,0.65,0.55,1121.19,201.81,1323.0,0.0
1243,2723.0,2025-11-29,Y,FG - Clarifying Concentrate - 10ml,2.0,NaT,Serum,661.02,0.65,0.55,594.92,107.08,702.0,0.0
1244,2723.0,2025-11-29,Y,FG - Copper Peptide Serum - 10ml,4.0,NaT,Serum,1559.32,0.65,0.55,2806.78,505.22,3312.0,0.0
1245,2723.0,2025-11-29,Y,FG - Radiance Face Oil - 10ml,4.0,NaT,Oil,1228.81,0.65,0.55,2211.86,398.14,2610.0,0.0
1246,2723.0,2025-11-29,Y,FG - VitC Body Oil - 100ml,3.0,NaT,Body,1144.07,0.65,0.55,1544.49,278.01,1822.5,0.0

In [ ]:
string_columns = ['account_code', 'product_name', 'category']
for col in string_columns:
    df[col] = df[col].astype(pd.StringDtype()) #converting objects to strings
df.dtypes

order_id                   float64
date                datetime64[ns]
account_code        string[python]
product_name        string[python]
quantity                   float64
appointment_date    datetime64[ns]
category            string[python]
unit_price                 float64
treat_disc                 float64
retail_disc                 object
base_price                 float64
gst                        float64
final_price                float64
check_rt                   float64
dtype: object

In [ ]:
print(df['retail_disc'].unique()[:20]) #checking why retail_disc is object type instead of float

[0.36 0.4 nan 0.25 0.5 0.2 '-' 0.35 0.45 0.55 0.27 0.3 0.6 0.4667 0.525
 0.425]

In [ ]:
df['retail_disc'] = df['retail_disc'].astype(str).str.replace(',', '', regex=False).str.strip()
df['retail_disc'] = df['retail_disc'].replace(['-', '–', '—', ''], np.nan)  # Replace various dash types
df['retail_disc'] = pd.to_numeric(df['retail_disc'], errors='coerce')
print(df['retail_disc'].unique()[:20])
df.dtypes

[0.36   0.4       nan 0.25   0.5    0.2    0.35   0.45   0.55   0.27
 0.3    0.6    0.4667 0.525  0.425 ]

order_id                   float64
date                datetime64[ns]
account_code        string[python]
product_name        string[python]
quantity                   float64
appointment_date    datetime64[ns]
category            string[python]
unit_price                 float64
treat_disc                 float64
retail_disc                float64
base_price                 float64
gst                        float64
final_price                float64
check_rt                   float64
dtype: object

In [ ]:
df['date'] = pd.to_datetime(df['date']) #converting dates data
df['appointment_date'] = pd.to_datetime(df['appointment_date'], errors='coerce')
df.dtypes

order_id                   float64
date                datetime64[ns]
account_code        string[python]
product_name        string[python]
quantity                   float64
appointment_date    datetime64[ns]
category            string[python]
unit_price                 float64
treat_disc                 float64
retail_disc                float64
base_price                 float64
gst                        float64
final_price                float64
check_rt                   float64
dtype: object

In [ ]:
missing_product = df['product_name'].isna()
missing_product_count = missing_product.sum()
missing_account =df['account_code'].isna()
missing_account_count=missing_account.sum()
missing_category=df['category'].isna()
missing_category_count=missing_category.sum()
missing_unitPrice=df['unit_price'].isna()
missing_unitPrice_count=missing_unitPrice.sum()
print(f"Rows with missing product: {missing_product_count}")
print(f"Rows with missing account: {missing_account_count}")
print(f"Rows with missing category: {missing_category_count}")
#checking if there are any rows with missing product , acc and category. None , so not dropping any rows

Rows with missing product: 0
Rows with missing account: 0
Rows with missing category: 1

In [ ]:
prod = df.loc[df['category'].isna(), 'product_name'].iloc[0]
# Get a non‑null category for that product (first available)
cat = df[df['product_name'] == prod]['category'].dropna().iloc[0]
# Fill all missing rows for that product with that category
df.loc[df['category'].isna(), 'category'] = cat

In [ ]:
#evaluating numeric columns missing vals
missing_quantity_count=df['quantity'].isna().sum()
print("Rows with missing quantity",missing_quantity_count)
missing_unitPrice_count=df['unit_price'].isna().sum()
print("Rows with missing Unit Price",missing_unitPrice_count)
missing_treatDisc_count=df['treat_disc'].isna().sum()
print("Rows with missing Treat Discount",missing_treatDisc_count)
missing_retailDisc_count=df['retail_disc'].isna().sum()
print("Rows with missing Retail Discount",missing_retailDisc_count)

Rows with missing quantity 37
Rows with missing Unit Price 1
Rows with missing Treat Discount 551
Rows with missing Retail Discount 10

In [ ]:
df['quantity']=df['quantity'].fillna(value=0)
df['unit_price']=df['unit_price'].fillna(value=0)
df['treat_disc']=df['treat_disc'].fillna(value=0)
df['retail_disc']=df['retail_disc'].fillna(value=0)
missing_quantity_count=df['quantity'].isna().sum()
print("Rows with missing quantity",missing_quantity_count)
missing_unitPrice_count=df['unit_price'].isna().sum()
print("Rows with missing Unit Price",missing_unitPrice_count)
missing_treatDisc_count=df['treat_disc'].isna().sum()
print("Rows with missing Treat Discount",missing_treatDisc_count)
missing_retailDisc_count=df['retail_disc'].isna().sum()
print("Rows with missing Retail Discount",missing_retailDisc_count)
#handling na values for numeric fields except order_id

Rows with missing quantity 0
Rows with missing Unit Price 0
Rows with missing Treat Discount 0
Rows with missing Retail Discount 0

In [ ]:
df[df['order_id']==2702]

,order_id,date,account_code,product_name,quantity,appointment_date,category,unit_price,treat_disc,retail_disc,base_price,gst,final_price,check_rt
1092,2702.0,2025-11-28,W,FG - Eye Care Ritual Kit,1.0,NaT,Kit,10169.49,0.3,0.3,5084.75,915.25,6000.0,1.0
1093,2702.0,2025-11-28,W,FG - Radiance AntiOx Treatment Kit,2.0,NaT,Kit,10169.49,0.3,0.3,10169.49,1830.51,12000.0,1.0
1104,2702.0,2025-11-28,W,FG - MultiPeptide Ageing Treatment Kit,1.0,NaT,Kit,10169.49,0.3,0.3,5084.75,915.25,6000.0,1.0
1105,2702.0,2025-11-28,W,FG - Clarifying Mineral Treatment Kit,0.0,NaT,Kit,0.00,0.0,0.0,NaN,NaN,NaN,NaN

In [ ]:
#now lets standardise base_price , gst and final_price fields
#compute base price = unit_price*quantity*(1-treat_disc)*(1-retaildisc)
df['base_price'] = df['unit_price'] * df['quantity'] * (1 - df['treat_disc']) * (1 - df['retail_disc'])
df['base_price'] = df['base_price'].round(2)
#  Calculating GST as 18% of rounded base_price
df['gst'] = (df['base_price'] * 0.18).round(2)
# Calculate final_price = base_price + GST
df['final_price'] = (df['base_price'] + df['gst']).round(2)

In [ ]:
#standardised the data

In [ ]:
df.to_excel('/content/drive/MyDrive/Colab Notebooks/Aminu_Assignment/Aminu_task1.xlsx', sheet_name='Cleaned Data', index=False)
print("Completed task 1")

Completed task 1

NameError: name 'df' is not defined